# Generated by Django 5.1.7 on 2025-03-17 06:12

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_leavetype_leaveapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='time',
            field=models.DateTimeField(default=employee.models.get_kolkata_time),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='time',
            field=models.DateTimeField(default=employee.models.get_kolkata_time),
        ),
    ]
