# Generated by Django 5.1.7 on 2025-03-20 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_checkin_time_alter_checkout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 11, 24, 20, 524190, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 11, 24, 20, 555444, tzinfo=datetime.timezone.utc)),
        ),
    ]
